import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./supabase-config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let admin=null,projects=[],customers=[];
function status(t,bad=false){$("mgmtStatus").textContent=t||"";$("mgmtStatus").className="mgmt-status"+(bad?" error":"")}
function loginStatus(t,bad=false){$("loginStatus").textContent=t||"";$("loginStatus").className="mgmt-status"+(bad?" error":"")}
async function requireAdmin(){
 const {data:{session}}=await supabase.auth.getSession();
 if(!session)return false;
 const {data:p,error}=await supabase.from("profiles").select("account_type,full_name").eq("id",session.user.id).maybeSingle();
 if(error||p?.account_type!=="admin"){await supabase.auth.signOut();loginStatus("This account is not authorised for TW&D management access.",true);return false}
 admin=session.user;$("loginPanel").hidden=true;$("appPanel").hidden=false;$("signout").hidden=false;$("adminIdentity").textContent=(p.full_name||session.user.email)+" • ADMIN";await loadAll();return true;
}
async function loadAll(){
 const [c,p,r]=await Promise.all([
  supabase.from("profiles").select("id,full_name,phone,account_type").order("created_at",{ascending:false}),
  supabase.from("projects").select("*").order("updated_at",{ascending:false}),
  supabase.from("service_requests").select("id,customer_id,subject,message,status,created_at").order("created_at",{ascending:false}).limit(30)
 ]);
 if(c.error||p.error||r.error){status((c.error||p.error||r.error).message,true);return}
 customers=c.data||[];projects=p.data||[];
 renderCustomers();renderProjects();renderRequests(r.data||[]);populateCustomerSelects();populateQuoteProjects();
}
function renderCustomers(){$("customersList").innerHTML=customers.map(x=>'<div class="mgmt-row"><strong>'+esc(x.full_name||"Unnamed customer")+'</strong><span>'+esc(x.phone||"No phone")+" • "+esc(x.account_type)+" • "+esc(x.id)+"</span></div>").join("")||"<p>No accounts yet.</p>"}
function renderProjects(){$("projectsList").innerHTML=projects.map(x=>'<div class="mgmt-row '+(window.selectedProjectId===x.id?"selected":"")+'" data-id="'+x.id+'"><strong>'+esc(x.project_name)+'</strong><span>'+esc(x.project_code||"No code")+" • "+esc(x.status)+" • "+x.progress+"%</span></div>").join("")||"<p>No projects assigned yet.</p>";document.querySelectorAll("[data-id]").forEach(el=>el.onclick=()=>openProject(el.dataset.id))}
function renderRequests(rows){$("requestsList").innerHTML=rows.map(x=>'<div class="mgmt-row"><strong>'+esc(x.subject)+'</strong><span>'+esc(customerName(x.customer_id))+" • "+esc(x.status)+"</span><small>"+esc(x.message)+"</small><button class='mgmt-btn small' data-request='"+x.id+"'>Close & Notify</button></div>").join("")||"<p>No service requests.</p>";document.querySelectorAll("[data-request]").forEach(b=>b.onclick=()=>closeRequest(b.dataset.request,rows.find(x=>x.id===b.dataset.request)))}
function customerName(id){return customers.find(x=>x.id===id)?.full_name||id}
function populateCustomerSelects(){const opts='<option value="">Select customer</option>'+customers.filter(x=>x.account_type!=="admin").map(x=>'<option value="'+x.id+'">'+esc(x.full_name||x.id)+'</option>').join("");$("projectCustomer").innerHTML=opts;$("quoteCustomer").innerHTML=opts}
function populateQuoteProjects(){ $("quoteProject").innerHTML='<option value="">No project</option>'+projects.map(x=>'<option value="'+x.id+'">'+esc(x.project_name)+'</option>').join("")}
async function openProject(id){
 window.selectedProjectId=id;renderProjects();const p=projects.find(x=>x.id===id);if(!p)return;
 $("projectEditor").hidden=false;$("selectedProjectTitle").textContent=p.project_name;
 $("projectCustomer").value=p.customer_id;$("projectName").value=p.project_name;$("projectCode").value=p.project_code||"";$("projectService").value=p.service_type||"";$("projectLocation").value=p.location||"";$("projectStatus").value=p.status;$("projectProgress").value=p.progress;$("projectDescription").value=p.description||"";
 $("reportDate").value=new Date().toISOString().slice(0,10);$("reportProgress").value=p.progress;
 const [r,d]=await Promise.all([supabase.from("project_reports").select("*").eq("project_id",id).order("report_date",{ascending:false}),supabase.from("project_documents").select("*").eq("project_id",id).order("uploaded_at",{ascending:false})]);
 $("reportsList").innerHTML='<h3>Private reports</h3>'+(r.data||[]).map(x=>'<div class="report-item"><strong>'+esc(x.report_title)+'</strong><small>'+esc(x.report_date)+" • "+(x.progress??"")+"%</small><div>"+esc(x.report_body).replace(/\n/g,"<br>")+"</div></div>").join("")||"<p>No reports yet.</p>";
 $("documentsList").innerHTML='<h3>Private documents</h3>'+(d.data||[]).map(x=>'<div class="mgmt-row"><strong>'+esc(x.document_name)+'</strong><span>'+esc(x.description||x.document_type||"Private project file")+'</span></div>').join("")||"<p>No private documents yet.</p>";
}
$("loginForm").onsubmit=async e=>{e.preventDefault();loginStatus("Signing in…");const {error}=await supabase.auth.signInWithPassword({email:$("adminEmail").value.trim(),password:$("adminPassword").value});if(error){loginStatus(error.message,true);return}if(!(await requireAdmin())){}};
$("signout").onclick=async()=>{await supabase.auth.signOut();location.reload()};
$("newProjectBtn").onclick=()=>{window.selectedProjectId=null;$("projectEditor").hidden=false;$("selectedProjectTitle").textContent="New Project";$("projectForm").reset();$("projectProgress").value=0;$("projectStatus").value="REQUESTED";$("reportForm").reset();$("reportDate").value=new Date().toISOString().slice(0,10)};
$("projectForm").onsubmit=async e=>{e.preventDefault();const payload={customer_id:$("projectCustomer").value,project_name:$("projectName").value.trim(),project_code:$("projectCode").value.trim()||null,service_type:$("projectService").value.trim(),location:$("projectLocation").value.trim(),status:$("projectStatus").value,progress:Number($("projectProgress").value),description:$("projectDescription").value.trim(),updated_at:new Date().toISOString()};let q=window.selectedProjectId?await supabase.from("projects").update(payload).eq("id",window.selectedProjectId):await supabase.from("projects").insert(payload).select().single();if(q.error){status(q.error.message,true);return}status("Project saved.");await loadAll();if(q.data?.id)await openProject(q.data.id);else if(window.selectedProjectId)await openProject(window.selectedProjectId)};
$("reportForm").onsubmit=async e=>{e.preventDefault();if(!window.selectedProjectId)return status("Choose a project first.",true);const p=projects.find(x=>x.id===window.selectedProjectId);const progress=$("reportProgress").value===""?p.progress:Number($("reportProgress").value);const ins=await supabase.from("project_reports").insert({project_id:p.id,customer_id:p.customer_id,report_title:$("reportTitle").value.trim(),report_body:$("reportBody").value.trim(),progress,report_date:$("reportDate").value});if(ins.error){status(ins.error.message,true);return}await supabase.from("projects").update({progress,updated_at:new Date().toISOString()}).eq("id",p.id);await supabase.from("notifications").insert({customer_id:p.customer_id,title:"New project progress report",message:"A new private progress report is available for "+p.project_name+" in your TW&D account."});$("reportForm").reset();$("reportDate").value=new Date().toISOString().slice(0,10);status("Private report published and customer notified.");await loadAll();await openProject(p.id)};
$("documentForm").onsubmit=async e=>{e.preventDefault();if(!window.selectedProjectId)return status("Choose a project first.",true);const p=projects.find(x=>x.id===window.selectedProjectId),file=$("projectFile").files[0];if(!file)return;const path=p.id+"/"+Date.now()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const up=await supabase.storage.from("project-private").upload(path,file,{upsert:false});if(up.error){status(up.error.message,true);return}const ins=await supabase.from("project_documents").insert({project_id:p.id,customer_id:p.customer_id,document_name:file.name,document_type:file.type,storage_path:path,description:$("documentDescription").value.trim()});if(ins.error){await supabase.storage.from("project-private").remove([path]);status(ins.error.message,true);return}await supabase.from("notifications").insert({customer_id:p.customer_id,title:"New private project document",message:"A new project document has been added to "+p.project_name+" in your secure TW&D account."});$("documentForm").reset();status("Private document uploaded and customer notified.");await openProject(p.id)};
$("quoteForm").onsubmit=async e=>{e.preventDefault();const customer=$("quoteCustomer").value;const ins=await supabase.from("quotations").insert({customer_id:customer,project_id:$("quoteProject").value||null,quotation_number:$("quoteNumber").value.trim(),amount:Number($("quoteAmount").value),status:$("quoteStatus").value,notes:$("quoteNotes").value.trim()});if(ins.error){status(ins.error.message,true);return}await supabase.from("notifications").insert({customer_id:customer,title:"Quotation update",message:"Quotation "+$("quoteNumber").value.trim()+" has been added to your TW&D account."});$("quoteForm").reset();status("Quotation saved and customer notified.");};
async function closeRequest(id,row){await supabase.from("service_requests").update({status:"RESPONDED",updated_at:new Date().toISOString()}).eq("id",id);await supabase.from("notifications").insert({customer_id:row.customer_id,title:"Service request update",message:"Your request '"+row.subject+"' has been reviewed by TW&D. Please check your account for the latest update or contact the office if further discussion is required."});status("Request updated and customer notified.");await loadAll()}
(async()=>{await requireAdmin()})();
