name: twd_engineering_mobile
description: TW&D Engineering Consult & Services Ltd mobile application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2

flutter:
  uses-material-design: true
